### PR TITLE
Add verification endpoint to API

### PR DESCRIPTION
**Pull request by mehradsadeghi**

### CODE REVIEW

**Comment by willbrowningme** [comment]
Thanks, looks good, will merge tomorrow!

**Comment by mehradsadeghi** [comment]
Yes. 
I'm using AnonAddy as a (single) server which my application (let's call it MyApp) is in communication through its http API.

The verification email that is sent to end users contains a verification link which sends the user to AnonAddy's web GUI. Since MyApp's users should no be able to access AnonAddy's GUI, I need an API endpoint that MyApp can verify email addresses.

I implemented the solution in a way than fulfills my use case, but it's not quite a general purpose approach. 

What do you recommend ?

**Comment by mehradsadeghi** [comment]
In order to implement a complete solution I will have to modify verification email template and replace my webapp address instead of AnonAddy's. 

If we could come up with an approach that the `RecipientController@store` returns the verification hash and the `VerificationController@verify` receives the hash and verifies the email address, it would be great.

**Comment by mehradsadeghi** [comment]
> I think a new `.env` variable e.g. `ANONADDY_AUTO_VERIFY_NEW_RECIPIENTS=true` that when set will simply create recipients with `'email_verified_at' => now()` might be better.
> 
> As you said, I don't think this is a common use case and wouldn't be recommended in most cases as it could be a security issue and defeats the entire purpose of email verification as it doesn't actually verify the user controls the email.

I agree. 
I'll change the implementation later today.

**Comment by mehradsadeghi** [comment]
@willbrowningme 
Hi will, Hope you're doing well.

I've pushed a couple of unwanted files into this PR accidentally. I contacted GitHub's support to find out how I can remove these files. Apparently they need your authorization to do so. 

Could you please submit a confirmation comment in this PR... ?

**Comment by willbrowningme** [comment]
@mehradsadeghi yes no problem, here is the confirmation comment for the files to be removed.

**Comment by mehradsadeghi** [comment]
@willbrowningme 

Hi, Apologies for the disturbance again.
Apparently GitHub support needs your authorization to delete the whole PR (not just `files` that you mentioned in the last comment).

Part of GitHub support's response to me:

> Apologies, but could you go back to the repository admin and clarify that we need to delete the PR entirely?
> They've given authorization for us to remove specific files, but that is not possible - we need to delete the whole PR.

I'd appreciate if you mention authorization to delete the whole PR.

**Comment by willbrowningme** [comment]
@mehradsadeghi yes I authorise for this entire PR to be deleted.

**Pull request closed without merging**
